Var
L: caractere
Inicio
L <- Java
Escreval ("Olá, eu sou o Cristian")
Escreval ("Estudo programação a pouco tempo")
Escreval ("Estou focado na linguagem: ", L, " , lógica e algoritmos!")
Escreval ("Aqui postarei meus projetos")


<!---
Cristianrafas/Cristianrafas is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
